<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <Prefer32Bit>false</Prefer32Bit>
    <LangVersion>7.3</LangVersion>
    <AssemblyName>TcpMapRemoteTest</AssemblyName>
    <RootNamespace>TcpMapRemoteTest</RootNamespace>
  </PropertyGroup>
</Project>
