//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinsockPacketEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinsockPacketEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; id=&quot;flag-icons-cn&quot; viewBox=&quot;0 0 640 480&quot;&gt;&lt;defs&gt;&lt;path id=&quot;cn-a&quot; fill=&quot;#ff0&quot; d=&quot;M-.6.8 0-1 .6.8-1-.3h2z&quot;/&gt;&lt;/defs&gt;&lt;path fill=&quot;#ee1c25&quot; d=&quot;M0 0h640v480H0z&quot;/&gt;&lt;use xlink:href=&quot;#cn-a&quot; width=&quot;30&quot; height=&quot;20&quot; transform=&quot;matrix(71.9991 0 0 72 120 120)&quot;/&gt;&lt;use xlink:href=&quot;#cn-a&quot; width=&quot;30&quot; height=&quot;20&quot; transform=&quot;matrix(-12.33562 -20.5871 20.58684 -12.33577 240.3 48)&quot;/&gt;&lt;use xlink:href=&quot;#cn-a&quot; width=&quot;30&quot; height=&quot;20&quot; transform=&quot;matrix(-3.38573 -23.75998 23.75968 -3.38578 288 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Flag_CN {
            get {
                return ResourceManager.GetString("Flag_CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg viewBox=&quot;0 0 1024 1024&quot;&gt;&lt;path d=&quot;M640.1 448.2m-59.1 0a59.1 59.1 0 1 0 118.2 0 59.1 59.1 0 1 0-118.2 0Z&quot; fill=&quot;#FFFFFF&quot;&gt;&lt;/path&gt;&lt;path d=&quot;M384.1 448.2m-59.1 0a59.1 59.1 0 1 0 118.2 0 59.1 59.1 0 1 0-118.2 0Z&quot; fill=&quot;#FFFFFF&quot;&gt;&lt;/path&gt;&lt;path d=&quot;M407.2 674.7s-17.3 81.4-79.6 58.7V801h368.7v-67.6s-56.5 22.3-79.4-58.7H407.2z&quot; fill=&quot;#515F79&quot;&gt;&lt;/path&gt;&lt;path d=&quot;M916 679H110c-6.6 0-12-5.4-12-12V541.2c0-6.6 5.4-12 12-12h806c6.6 0 12 5.4 12 12V667c0 6.6-5.4 12-12 12z&quot; fill=&quot;#6F82A3&quot;&gt;&lt;/path&gt;&lt;path d=&quot;M928 578.9H98V115.1c0-9 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Flag_Local {
            get {
                return ResourceManager.GetString("Flag_Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg viewBox=&quot;0 0 640 480&quot;&gt;&lt;!-- 条纹背景（7红+6白） --&gt;&lt;rect width=&quot;741&quot; height=&quot;390&quot; fill=&quot;#B22234&quot;/&gt;&lt;rect width=&quot;741&quot; height=&quot;30&quot; y=&quot;30&quot; fill=&quot;#FFFFFF&quot;/&gt;&lt;rect width=&quot;741&quot; height=&quot;30&quot; y=&quot;60&quot; fill=&quot;#B22234&quot;/&gt;&lt;rect width=&quot;741&quot; height=&quot;30&quot; y=&quot;90&quot; fill=&quot;#FFFFFF&quot;/&gt;&lt;rect width=&quot;741&quot; height=&quot;30&quot; y=&quot;120&quot; fill=&quot;#B22234&quot;/&gt;&lt;rect width=&quot;741&quot; height=&quot;30&quot; y=&quot;150&quot; fill=&quot;#FFFFFF&quot;/&gt;&lt;rect width=&quot;741&quot; height=&quot;30&quot; y=&quot;180&quot; fill=&quot;#B22234&quot;/&gt;&lt;rect width=&quot;741&quot; height=&quot;30&quot; y=&quot;210&quot; fill=&quot;#FFFFFF&quot;/&gt;&lt;rect width=&quot;741&quot; height=&quot;30&quot; y=&quot;240&quot; fill= [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Flag_US {
            get {
                return ResourceManager.GetString("Flag_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg viewBox=&quot;0 0 64 41&quot;&gt;&lt;g transform=&quot;translate(0 1)&quot; fill=&quot;none&quot;&gt;&lt;ellipse fill=&quot;#f5f5f5&quot; cx=&quot;32&quot; cy=&quot;33&quot; rx=&quot;32&quot; ry=&quot;7&quot;&gt;&lt;/ellipse&gt;&lt;g stroke=&quot;#d9d9d9&quot;&gt;&lt;path d=&quot;M55 12.76L44.854 1.258C44.367.474 43.656 0 42.907 0H21.093c-.749 0-1.46.474-1.947 1.257L9 12.761V22h46v-9.24z&quot;&gt;&lt;/path&gt;&lt;path d=&quot;M41.613 15.931c0-1.605.994-2.93 2.227-2.931H55v18.137C55 33.26 53.68 35 52.05 35h-40.1C10.32 35 9 33.259 9 31.137V13h11.16c1.233 0 2.227 1.323 2.227 2.928v.022c0 1.605 1.005 2.901 2.237 2.901h14.752c1.232 0 2.237-1.308 2.237 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string icon_empty {
            get {
                return ResourceManager.GetString("icon_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg viewBox=&quot;0 0 64 41&quot;&gt;&lt;g transform=&quot;translate(0 1)&quot; fill=&quot;none&quot;&gt;&lt;ellipse fill=&quot;#272727&quot; cx=&quot;32&quot; cy=&quot;33&quot; rx=&quot;32&quot; ry=&quot;7&quot;&gt;&lt;/ellipse&gt;&lt;g stroke=&quot;#3e3e3e&quot;&gt;&lt;path d=&quot;M55 12.76L44.854 1.258C44.367.474 43.656 0 42.907 0H21.093c-.749 0-1.46.474-1.947 1.257L9 12.761V22h46v-9.24z&quot;&gt;&lt;/path&gt;&lt;path d=&quot;M41.613 15.931c0-1.605.994-2.93 2.227-2.931H55v18.137C55 33.26 53.68 35 52.05 35h-40.1C10.32 35 9 33.259 9 31.137V13h11.16c1.233 0 2.227 1.323 2.227 2.928v.022c0 1.605 1.005 2.901 2.237 2.901h14.752c1.232 0 2.237-1.308 2.237 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string icon_empty_dark {
            get {
                return ResourceManager.GetString("icon_empty_dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg viewBox=&quot;0 0 1024 1024&quot;&gt;&lt;path d=&quot;M431.81 891.72L73.74 526.85a21.53 21.53 0 0 1 0-29.7l358.07-364.87c13.41-14.09 37.14-4.6 37.14 14.85v197.29h465.71A21.54 21.54 0 0 1 956.2 366v292a21.54 21.54 0 0 1-21.54 21.54H469v197.33c0 19.45-23.78 28.94-37.19 14.85z&quot; fill=&quot;#1296db&quot;&gt;&lt;/path&gt;&lt;/svg&gt; 的本地化字符串。
        /// </summary>
        internal static string Recv {
            get {
                return ResourceManager.GetString("Recv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg viewBox=&quot;0 0 1024 1024&quot;&gt;&lt;path d=&quot;M516.63443469 832.282072l505.51128772-334.76430522-505.51128772-334.76430522 0 164.17023984-502.92215271 0 0 337.10511326 502.92215271 0z&quot; fill=&quot;#36ab60&quot;&gt;&lt;/path&gt;&lt;/svg&gt; 的本地化字符串。
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap wpe {
            get {
                object obj = ResourceManager.GetObject("wpe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
