//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinsockPacketEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinsockPacketEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 -----BEGIN CERTIFICATE-----
        ///MIIDxDCCAqygAwIBAgIRAIf2ANuMpaWwEskuAGzy3vEwDQYJKoZIhvcNAQELBQAw
        ///azELMAkGA1UEBhMCQ04xETAPBgNVBAgTCFNoYW5nSGFpMREwDwYDVQQHEwhTaGFu
        ///Z0hhaTESMBAGA1UEChMJd3BlNjQuY29tMRIwEAYDVQQLEwl3cGU2NC5jb20xDjAM
        ///BgNVBAMTBVdQRTY0MCAXDTI1MTEwNzA3NDgyNFoYDzIxMjUxMDE0MDc0ODI0WjBr
        ///MQswCQYDVQQGEwJDTjERMA8GA1UECBMIU2hhbmdIYWkxETAPBgNVBAcTCFNoYW5n
        ///SGFpMRIwEAYDVQQKEwl3cGU2NC5jb20xEjAQBgNVBAsTCXdwZTY0LmNvbTEOMAwG
        ///A1UEAxMFV1BFNjQwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCzUw/2
        ///raiRAWqEgPbL3VBmsVYM7 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Cert_Ca {
            get {
                return ResourceManager.GetString("Cert_Ca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 -----BEGIN RSA PRIVATE KEY-----
        ///MIIEowIBAAKCAQEAs1MP9q2okQFqhID2y91QZrFWDO9kuw5IxxX/RuOBU29fmJp1
        ///OmtspfAgWSXWL2tc0r15GTA56sL6C0dD4YW+t5BJnU9wkhuibbMw0bufZDtlN191
        ///1XWQWyfjTL4RTby2kPOd+zWuejMsXfc6R4VJszbGAmULwHIinLptsrDf8aWvvd33
        ///jCv/6Z+e5vvtFgP1kV6k2PYrmGI+Udt9mrX2sYUjEmWPEO1ZJKLgPUatFcNSOF3K
        ////npzSHArwXsQwGCFXQKL4VwDQxuZIQqfa1LLtlQ13F8pY7He1GKYw079Zi8DXllk
        ///en79NosQMqjD8MpmsnqbdCcqmcPhaPzVTbipvQIDAQABAoIBAA2+fQe8EaJjiGV1
        ///ePTxFnt4dg7xvje0BZH0tqcZQs1BSQNqOzfqCd7CA8ixZLQnt2qTiReMIbRDk2SP
        ///5rz/QjnRfkLnVspsA [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Cert_Key {
            get {
                return ResourceManager.GetString("Cert_Key", resourceCulture);
            }
        }
        
    }
}
