//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPELibrary.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.13.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FilterConfig_CheckNotShow {
            get {
                return ((bool)(this["FilterConfig_CheckNotShow"]));
            }
            set {
                this["FilterConfig_CheckNotShow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FilterConfig_CheckSocket {
            get {
                return ((bool)(this["FilterConfig_CheckSocket"]));
            }
            set {
                this["FilterConfig_CheckSocket"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FilterConfig_CheckIP {
            get {
                return ((bool)(this["FilterConfig_CheckIP"]));
            }
            set {
                this["FilterConfig_CheckIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FilterConfig_CheckPort {
            get {
                return ((bool)(this["FilterConfig_CheckPort"]));
            }
            set {
                this["FilterConfig_CheckPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FilterConfig_CheckHead {
            get {
                return ((bool)(this["FilterConfig_CheckHead"]));
            }
            set {
                this["FilterConfig_CheckHead"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FilterConfig_CheckData {
            get {
                return ((bool)(this["FilterConfig_CheckData"]));
            }
            set {
                this["FilterConfig_CheckData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FilterConfig_CheckSize {
            get {
                return ((bool)(this["FilterConfig_CheckSize"]));
            }
            set {
                this["FilterConfig_CheckSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FilterConfig_CheckSocket_Value {
            get {
                return ((string)(this["FilterConfig_CheckSocket_Value"]));
            }
            set {
                this["FilterConfig_CheckSocket_Value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FilterConfig_CheckIP_Value {
            get {
                return ((string)(this["FilterConfig_CheckIP_Value"]));
            }
            set {
                this["FilterConfig_CheckIP_Value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FilterConfig_CheckPort_Value {
            get {
                return ((string)(this["FilterConfig_CheckPort_Value"]));
            }
            set {
                this["FilterConfig_CheckPort_Value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FilterConfig_CheckHead_Value {
            get {
                return ((string)(this["FilterConfig_CheckHead_Value"]));
            }
            set {
                this["FilterConfig_CheckHead_Value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FilterConfig_CheckData_Value {
            get {
                return ((string)(this["FilterConfig_CheckData_Value"]));
            }
            set {
                this["FilterConfig_CheckData_Value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0-99;100")]
        public string FilterConfig_CheckLength_Value {
            get {
                return ((string)(this["FilterConfig_CheckLength_Value"]));
            }
            set {
                this["FilterConfig_CheckLength_Value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HookConfig_HookWS1_Send {
            get {
                return ((bool)(this["HookConfig_HookWS1_Send"]));
            }
            set {
                this["HookConfig_HookWS1_Send"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HookConfig_HookWS1_SendTo {
            get {
                return ((bool)(this["HookConfig_HookWS1_SendTo"]));
            }
            set {
                this["HookConfig_HookWS1_SendTo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HookConfig_HookWS1_Recv {
            get {
                return ((bool)(this["HookConfig_HookWS1_Recv"]));
            }
            set {
                this["HookConfig_HookWS1_Recv"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HookConfig_HookWS1_RecvFrom {
            get {
                return ((bool)(this["HookConfig_HookWS1_RecvFrom"]));
            }
            set {
                this["HookConfig_HookWS1_RecvFrom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HookConfig_HookWSA_Send {
            get {
                return ((bool)(this["HookConfig_HookWSA_Send"]));
            }
            set {
                this["HookConfig_HookWSA_Send"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HookConfig_HookWSA_SendTo {
            get {
                return ((bool)(this["HookConfig_HookWSA_SendTo"]));
            }
            set {
                this["HookConfig_HookWSA_SendTo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HookConfig_HookWSA_Recv {
            get {
                return ((bool)(this["HookConfig_HookWSA_Recv"]));
            }
            set {
                this["HookConfig_HookWSA_Recv"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HookConfig_HookWSA_RecvFrom {
            get {
                return ((bool)(this["HookConfig_HookWSA_RecvFrom"]));
            }
            set {
                this["HookConfig_HookWSA_RecvFrom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ListConfig_SocketList_AutoRoll {
            get {
                return ((bool)(this["ListConfig_SocketList_AutoRoll"]));
            }
            set {
                this["ListConfig_SocketList_AutoRoll"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ListConfig_SocketList_AutoClear {
            get {
                return ((bool)(this["ListConfig_SocketList_AutoClear"]));
            }
            set {
                this["ListConfig_SocketList_AutoClear"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public decimal ListConfig_SocketList_AutoClear_Value {
            get {
                return ((decimal)(this["ListConfig_SocketList_AutoClear_Value"]));
            }
            set {
                this["ListConfig_SocketList_AutoClear_Value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ListConfig_LogList_AutoRoll {
            get {
                return ((bool)(this["ListConfig_LogList_AutoRoll"]));
            }
            set {
                this["ListConfig_LogList_AutoRoll"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ListConfig_LogList_AutoClear {
            get {
                return ((bool)(this["ListConfig_LogList_AutoClear"]));
            }
            set {
                this["ListConfig_LogList_AutoClear"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public decimal ListConfig_LogList_AutoClear_Value {
            get {
                return ((decimal)(this["ListConfig_LogList_AutoClear_Value"]));
            }
            set {
                this["ListConfig_LogList_AutoClear_Value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SystemConfig_SpeedMode {
            get {
                return ((bool)(this["SystemConfig_SpeedMode"]));
            }
            set {
                this["SystemConfig_SpeedMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sequence")]
        public string SystemConfig_FilterList_Execute {
            get {
                return ((string)(this["SystemConfig_FilterList_Execute"]));
            }
            set {
                this["SystemConfig_FilterList_Execute"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ProxyConfig_EnableSOCKS5 {
            get {
                return ((bool)(this["ProxyConfig_EnableSOCKS5"]));
            }
            set {
                this["ProxyConfig_EnableSOCKS5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8889")]
        public ushort ProxyConfig_ProxyPort {
            get {
                return ((ushort)(this["ProxyConfig_ProxyPort"]));
            }
            set {
                this["ProxyConfig_ProxyPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ProxyConfig_EnableAuth {
            get {
                return ((bool)(this["ProxyConfig_EnableAuth"]));
            }
            set {
                this["ProxyConfig_EnableAuth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ProxyConfig_Auth_UserName {
            get {
                return ((string)(this["ProxyConfig_Auth_UserName"]));
            }
            set {
                this["ProxyConfig_Auth_UserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ProxyConfig_Auth_PassWord {
            get {
                return ((string)(this["ProxyConfig_Auth_PassWord"]));
            }
            set {
                this["ProxyConfig_Auth_PassWord"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ProxyConfig_LogList_AutoRoll {
            get {
                return ((bool)(this["ProxyConfig_LogList_AutoRoll"]));
            }
            set {
                this["ProxyConfig_LogList_AutoRoll"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ProxyConfig_LogList_AutoClear {
            get {
                return ((bool)(this["ProxyConfig_LogList_AutoClear"]));
            }
            set {
                this["ProxyConfig_LogList_AutoClear"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public decimal ProxyConfig_LogList_AutoClear_Value {
            get {
                return ((decimal)(this["ProxyConfig_LogList_AutoClear_Value"]));
            }
            set {
                this["ProxyConfig_LogList_AutoClear_Value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HookConfig_HookWS2_Send {
            get {
                return ((bool)(this["HookConfig_HookWS2_Send"]));
            }
            set {
                this["HookConfig_HookWS2_Send"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HookConfig_HookWS2_SendTo {
            get {
                return ((bool)(this["HookConfig_HookWS2_SendTo"]));
            }
            set {
                this["HookConfig_HookWS2_SendTo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HookConfig_HookWS2_Recv {
            get {
                return ((bool)(this["HookConfig_HookWS2_Recv"]));
            }
            set {
                this["HookConfig_HookWS2_Recv"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HookConfig_HookWS2_RecvFrom {
            get {
                return ((bool)(this["HookConfig_HookWS2_RecvFrom"]));
            }
            set {
                this["HookConfig_HookWS2_RecvFrom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ProxyConfig_ProxyList_NoRecord {
            get {
                return ((bool)(this["ProxyConfig_ProxyList_NoRecord"]));
            }
            set {
                this["ProxyConfig_ProxyList_NoRecord"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ProxyConfig_ClientList_DelClosed {
            get {
                return ((bool)(this["ProxyConfig_ClientList_DelClosed"]));
            }
            set {
                this["ProxyConfig_ClientList_DelClosed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ProxyConfig_ProxyIP_Auto {
            get {
                return ((bool)(this["ProxyConfig_ProxyIP_Auto"]));
            }
            set {
                this["ProxyConfig_ProxyIP_Auto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ProxyConfig_EXTProxy_EnableHttp {
            get {
                return ((bool)(this["ProxyConfig_EXTProxy_EnableHttp"]));
            }
            set {
                this["ProxyConfig_EXTProxy_EnableHttp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ProxyConfig_EXTProxy_EnableHttps {
            get {
                return ((bool)(this["ProxyConfig_EXTProxy_EnableHttps"]));
            }
            set {
                this["ProxyConfig_EXTProxy_EnableHttps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ProxyConfig_EXTProxy_HttpIP {
            get {
                return ((string)(this["ProxyConfig_EXTProxy_HttpIP"]));
            }
            set {
                this["ProxyConfig_EXTProxy_HttpIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ProxyConfig_EXTProxy_HttpsIP {
            get {
                return ((string)(this["ProxyConfig_EXTProxy_HttpsIP"]));
            }
            set {
                this["ProxyConfig_EXTProxy_HttpsIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ushort ProxyConfig_EXTProxy_HttpPort {
            get {
                return ((ushort)(this["ProxyConfig_EXTProxy_HttpPort"]));
            }
            set {
                this["ProxyConfig_EXTProxy_HttpPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ushort ProxyConfig_EXTProxy_HttpsPort {
            get {
                return ((ushort)(this["ProxyConfig_EXTProxy_HttpsPort"]));
            }
            set {
                this["ProxyConfig_EXTProxy_HttpsPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80,8080")]
        public string ProxyConfig_EXTProxy_AppointHttpPort {
            get {
                return ((string)(this["ProxyConfig_EXTProxy_AppointHttpPort"]));
            }
            set {
                this["ProxyConfig_EXTProxy_AppointHttpPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("443,8443")]
        public string ProxyConfig_EXTProxy_AppointHttpsPort {
            get {
                return ((string)(this["ProxyConfig_EXTProxy_AppointHttpsPort"]));
            }
            set {
                this["ProxyConfig_EXTProxy_AppointHttpsPort"] = value;
            }
        }
    }
}
