using System.ComponentModel;
using System.Text.Json;
using ModelContextProtocol.Server;

[McpServerToolType]
internal static class WpeTools
{
    [McpServerTool(Name = "wpe_status_get"), Description("Return the current WPE runtime status.")]
    public static Task<string> StatusGet(WpeGatewayClient gateway, CancellationToken cancellationToken) =>
        gateway.InvokeAsync("runtime.status", null, cancellationToken);

    [McpServerTool(Name = "wpe_capture_search"), Description("Search a bounded page of WPE packet metadata. mode is proxy or inject (default proxy); direction is retained for compatibility and must be any. Use wpe_packet_get for complete packet bytes.")]
    public static Task<string> CaptureSearch(WpeGatewayClient gateway, int? limit = null, string? cursor = null, string? mode = null, string? pattern = null, bool hex = false, string direction = "any", CancellationToken cancellationToken = default) =>
        gateway.InvokeAsync("capture.search", new PacketSearchInput(limit, cursor, mode, pattern, hex, direction), cancellationToken);

    [McpServerTool(Name = "wpe_packet_get"), Description("Get one captured packet with its complete current and original payload bytes as Base64. mode is proxy or inject (default proxy).")]
    public static Task<string> PacketGet(WpeGatewayClient gateway, long id, string? mode = null, bool includePayload = true, CancellationToken cancellationToken = default) =>
        gateway.InvokeAsync("capture.get", new PacketGetInput(id, mode, includePayload), cancellationToken);
    [McpServerTool(Name = "wpe_capture_find_next"), Description("Use WPE's native regex packet search to find the next match in the proxy or inject capture list, including byte offset metadata for highlighting. mode is proxy or inject (default proxy).")]
    public static Task<string> CaptureFindNext(WpeGatewayClient gateway, string pattern, bool hex = false, string mode = "proxy", int fromIndex = 0, int fromPosition = 0, CancellationToken cancellationToken = default) =>
        gateway.InvokeAsync("capture.findNext", new CaptureFindNextInput(pattern, hex, mode, fromIndex, fromPosition), cancellationToken);

    [McpServerTool(Name = "wpe_logs_list"), Description("List a bounded page of WPE logs. kind must be system, filter, proxy, or mcp.")]
    public static Task<string> LogsList(WpeGatewayClient gateway, string kind, int? limit = null, string? cursor = null, CancellationToken cancellationToken = default) =>
        gateway.InvokeAsync("logs.list", new LogListInput(kind, limit, cursor), cancellationToken);
    [McpServerTool(Name = "wpe_logs_all_list"), Description("List a single time-ordered page across all WPE system, filter, proxy, and MCP operational logs.")]
    public static Task<string> LogsAllList(WpeGatewayClient gateway, int? limit = null, string? cursor = null, CancellationToken cancellationToken = default) =>
        gateway.InvokeAsync("logs.all.list", new PageInput(limit, cursor), cancellationToken);

    [McpServerTool(Name = "wpe_filters_list"), Description("List WPE filters without modifying them.")]
    public static Task<string> FiltersList(WpeGatewayClient gateway, int? limit = null, string? cursor = null, CancellationToken cancellationToken = default) => gateway.InvokeAsync("filters.list", new PageInput(limit, cursor), cancellationToken);
    [McpServerTool(Name = "wpe_filter_get"), Description("Get one existing WPE filter as the same semantic rule object accepted by wpe_filter_rule_save, including its actual enabled state. id accepts its exact visible name or GUID.")]
    public static Task<string> FilterGet(WpeGatewayClient gateway, string id, CancellationToken cancellationToken = default) => gateway.InvokeAsync("filters.get", new FilterGetInput(id), cancellationToken);
    [McpServerTool(Name = "wpe_filter_stats_get"), Description("Get read-only runtime statistics for one existing WPE filter. id accepts its exact visible name or GUID.")]
    public static Task<string> FilterStatsGet(WpeGatewayClient gateway, string id, CancellationToken cancellationToken = default) => gateway.InvokeAsync("filters.stats.get", new FilterGetInput(id), cancellationToken);
    [McpServerTool(Name = "wpe_filter_set_enabled"), Description("Enable or disable one filter after local confirmation. id accepts its exact visible name or GUID.")]
    public static Task<string> FilterSetEnabled(WpeGatewayClient gateway, string id, bool enabled, string idempotencyKey, CancellationToken cancellationToken = default) => gateway.InvokeAsync("filters.setEnabled", new FilterSetEnabledInput(id, enabled, idempotencyKey), cancellationToken);
    [McpServerTool(Name = "wpe_filters_set_all_enabled"), Description("Enable or disable all existing WPE filters after local confirmation.")]
    public static Task<string> FiltersSetAllEnabled(WpeGatewayClient gateway, bool enabled, string idempotencyKey, CancellationToken cancellationToken = default) => gateway.InvokeAsync("filters.setAllEnabled", new FiltersSetAllEnabledInput(enabled, idempotencyKey), cancellationToken);
    [McpServerTool(Name = "wpe_filter_counts_reset"), Description("Reset existing WPE filters' runtime execution counts after local confirmation. This does not alter filter rules.")]
    public static Task<string> FilterCountsReset(WpeGatewayClient gateway, string idempotencyKey, CancellationToken cancellationToken = default) => gateway.InvokeAsync("filters.counts.reset", new FilterCountsResetInput(idempotencyKey), cancellationToken);
    [McpServerTool(Name = "wpe_filters_move"), Description("Move selected existing filters using WPE's native list-order behavior. direction must be top, up, down, or bottom. ids accepts exact visible names or GUIDs. Filter order affects execution order.")]
    public static Task<string> FiltersMove(WpeGatewayClient gateway, string[] ids, string direction, string idempotencyKey, CancellationToken cancellationToken = default) => gateway.InvokeAsync("filters.move", new FiltersMoveInput(ids, direction, idempotencyKey), cancellationToken);
    [McpServerTool(Name = "wpe_filters_copy"), Description("Copy selected existing WPE filters using the native list action after local confirmation. ids accepts exact visible names or GUIDs.")]
    public static Task<string> FiltersCopy(WpeGatewayClient gateway, string[] ids, string idempotencyKey, CancellationToken cancellationToken = default) => gateway.InvokeAsync("filters.copy", new FiltersCopyInput(ids, idempotencyKey), cancellationToken);
    [McpServerTool(Name = "wpe_filters_clear_all"), Description("Clear all existing WPE filters after local confirmation; WPE also shows its native destructive confirmation.")]
    public static Task<string> FiltersClearAll(WpeGatewayClient gateway, string idempotencyKey, CancellationToken cancellationToken = default) => gateway.InvokeAsync("filters.clearAll", new FilterCountsResetInput(idempotencyKey), cancellationToken);
    [McpServerTool(Name = "wpe_filter_create_from_capture"), Description("Create a filter from one existing captured WPE packet after local confirmation, matching WPE's native packet-to-filter action.")]
    public static Task<string> FilterCreateFromCapture(WpeGatewayClient gateway, long packetId, string idempotencyKey, CancellationToken cancellationToken = default) => gateway.InvokeAsync("filters.createFromCapture", new FilterCreateFromCaptureInput(packetId, idempotencyKey), cancellationToken);
    [McpServerTool(Name = "wpe_filter_create"), Description("Create a new empty WPE filter after local confirmation.")]
    public static Task<string> FilterCreate(WpeGatewayClient gateway, string idempotencyKey, CancellationToken cancellationToken = default) => gateway.InvokeAsync("filters.create", new FilterCreateInput(idempotencyKey), cancellationToken);
    [McpServerTool(Name = "wpe_filter_rule_save"), Description("Save a complete semantic WPE filter rule after local confirmation. action replace changes selected bytes and is required for byte substitutions; action change replaces the entire packet and requires contiguous modify cells from offset 0. Other actions are intercept, display, or hide. Advanced rules must explicitly set startFrom: position changes every match and makes modify offsets relative to the match anchor; head changes only the first match and uses absolute offsets. packetTypes is one or more of send, sendTo, recv, recvFrom, wsaSend, wsaSendTo, wsaRecv, wsaRecvFrom, tcpRequest, udpRequest, tcpResponse, udpResponse, tcp, udp, or all (all selects every type in the current mode). search and modify contain objects with zero-based offset and uppercase hexadecimal value such as 01. It does not change enabled state.")]
    public static Task<string> FilterRuleSave(WpeGatewayClient gateway, string filter, JsonElement rule, string idempotencyKey, CancellationToken cancellationToken = default) => gateway.InvokeAsync("filters.rule.save", new FilterRuleSaveInput(filter, rule, idempotencyKey), cancellationToken);
    [McpServerTool(Name = "wpe_filter_delete"), Description("Delete an existing WPE filter after local confirmation. id accepts its exact visible name or GUID.")]
    public static Task<string> FilterDelete(WpeGatewayClient gateway, string id, string idempotencyKey, CancellationToken cancellationToken = default) => gateway.InvokeAsync("filters.delete", new FilterDeleteInput(id, idempotencyKey), cancellationToken);
    [McpServerTool(Name = "wpe_account_set_enabled"), Description("Enable or disable one proxy account. id is the account record GUID returned by wpe_accounts_list; never pass the userName here.")]
    public static Task<string> AccountSetEnabled(WpeGatewayClient gateway, string id, bool enabled, string idempotencyKey, CancellationToken cancellationToken = default) => gateway.InvokeAsync("accounts.setEnabled", new AccountSetEnabledInput(id, enabled, idempotencyKey), cancellationToken);
    [McpServerTool(Name = "wpe_account_create"), Description("Create one WPE proxy account after local confirmation. userName is the new login-name text, not a GUID.")]
    public static Task<string> AccountCreate(WpeGatewayClient gateway, string userName, string password, bool enabled, bool limitLinksEnabled, int limitLinks, bool limitDevicesEnabled, int limitDevices, bool expiryEnabled, string? expiryTime, string idempotencyKey, CancellationToken cancellationToken = default) => gateway.InvokeAsync("accounts.create", new AccountCreateInput(userName, password, enabled, limitLinksEnabled, limitLinks, limitDevicesEnabled, limitDevices, expiryEnabled, expiryTime, idempotencyKey), cancellationToken);
    [McpServerTool(Name = "wpe_account_update"), Description("Update one proxy account after local confirmation. id is the account record GUID returned by wpe_accounts_list; userName is the login-name text used only to search wpe_accounts_list and cannot be changed here.")]
    public static Task<string> AccountUpdate(WpeGatewayClient gateway, string id, bool enabled, bool limitLinksEnabled, int limitLinks, bool limitDevicesEnabled, int limitDevices, bool expiryEnabled, string? expiryTime, string? password, string idempotencyKey, CancellationToken cancellationToken = default) => gateway.InvokeAsync("accounts.update", new AccountUpdateInput(id, enabled, limitLinksEnabled, limitLinks, limitDevicesEnabled, limitDevices, expiryEnabled, expiryTime, password, idempotencyKey), cancellationToken);
    [McpServerTool(Name = "wpe_account_delete"), Description("Delete one proxy account after local confirmation. id is the account record GUID returned by wpe_accounts_list; never pass the userName here.")]
    public static Task<string> AccountDelete(WpeGatewayClient gateway, string id, string idempotencyKey, CancellationToken cancellationToken = default) => gateway.InvokeAsync("accounts.delete", new AccountDeleteInput(id, idempotencyKey), cancellationToken);
    [McpServerTool(Name = "wpe_proxy_auth_set_enabled"), Description("Request a reversible proxy authentication setting change. WPE validates Only-WPC compatibility and persists the setting after local confirmation.")]
    public static Task<string> ProxyAuthSetEnabled(WpeGatewayClient gateway, bool enabled, string idempotencyKey, CancellationToken cancellationToken = default) => gateway.InvokeAsync("proxy.auth.setEnabled", new ProxyAuthSetEnabledInput(enabled, idempotencyKey), cancellationToken);
    [McpServerTool(Name = "wpe_proxy_http_set_enabled"), Description("Request a reversible HTTP proxy enable/disable change. WPE validates port compatibility and persists the setting after local confirmation.")]
    public static Task<string> ProxyHttpSetEnabled(WpeGatewayClient gateway, bool enabled, string idempotencyKey, CancellationToken cancellationToken = default) => gateway.InvokeAsync("proxy.http.setEnabled", new ProxyHttpSetEnabledInput(enabled, idempotencyKey), cancellationToken);
    [McpServerTool(Name = "wpe_proxy_max_connections_set"), Description("Request a reversible proxy maximum-connection limit change. WPE validates the current machine cap and persists the setting after local confirmation.")]
    public static Task<string> ProxyMaxConnectionsSet(WpeGatewayClient gateway, int maxConnection, string idempotencyKey, CancellationToken cancellationToken = default) => gateway.InvokeAsync("proxy.maxConnections.set", new ProxyMaxConnectionsSetInput(maxConnection, idempotencyKey), cancellationToken);
    [McpServerTool(Name = "wpe_proxy_socks5_port_set"), Description("Request a reversible SOCKS5 listening-port change. WPE validates range and HTTP-port conflicts, then persists after local confirmation.")]
    public static Task<string> ProxySocks5PortSet(WpeGatewayClient gateway, int port, string idempotencyKey, CancellationToken cancellationToken = default) => gateway.InvokeAsync("proxy.socks5Port.set", new ProxySocks5PortSetInput(port, idempotencyKey), cancellationToken);
    [McpServerTool(Name = "wpe_proxy_http_port_set"), Description("Request a reversible HTTP listening-port change. WPE validates that HTTP is enabled, checks range and SOCKS5 conflicts, then persists after local confirmation.")]
    public static Task<string> ProxyHttpPortSet(WpeGatewayClient gateway, int port, string idempotencyKey, CancellationToken cancellationToken = default) => gateway.InvokeAsync("proxy.httpPort.set", new ProxyHttpPortSetInput(port, idempotencyKey), cancellationToken);
    [McpServerTool(Name = "wpe_firewall_set_enabled"), Description("Request a reversible firewall enable/disable change. WPE applies and persists it only after local confirmation.")]
    public static Task<string> FirewallSetEnabled(WpeGatewayClient gateway, bool enabled, string idempotencyKey, CancellationToken cancellationToken = default) => gateway.InvokeAsync("firewall.setEnabled", new FirewallSetEnabledInput(enabled, idempotencyKey), cancellationToken);
    [McpServerTool(Name = "wpe_proxy_only_wpc_set_enabled"), Description("Request a reversible Only-WPC proxy setting change. WPE requires authentication when enabling and persists after local confirmation.")]
    public static Task<string> ProxyOnlyWpcSetEnabled(WpeGatewayClient gateway, bool enabled, string idempotencyKey, CancellationToken cancellationToken = default) => gateway.InvokeAsync("proxy.onlyWpc.setEnabled", new ProxyOnlyWpcSetEnabledInput(enabled, idempotencyKey), cancellationToken);
    [McpServerTool(Name = "wpe_executors_list"), Description("List WPE send and robot executor status without changing it.")]
    public static Task<string> ExecutorsList(WpeGatewayClient gateway, CancellationToken cancellationToken) => gateway.InvokeAsync("executors.list", null, cancellationToken);
    [McpServerTool(Name = "wpe_connections_list"), Description("List a bounded page of WPE connections.")]
    public static Task<string> ConnectionsList(WpeGatewayClient gateway, int? limit = null, string? cursor = null, CancellationToken cancellationToken = default) => gateway.InvokeAsync("connections.list", new PageInput(limit, cursor), cancellationToken);
    [McpServerTool(Name = "wpe_accounts_list"), Description("List proxy accounts including decrypted passwords. userName is optional login-name text for case-insensitive search; use the returned Id GUID for every other account tool.")]
    public static Task<string> AccountsList(WpeGatewayClient gateway, int? limit = null, string? cursor = null, string? userName = null, CancellationToken cancellationToken = default) => gateway.InvokeAsync("accounts.list", new AccountListInput(limit, cursor, userName), cancellationToken);
    [McpServerTool(Name = "wpe_account_get"), Description("Get one proxy account's configuration and login records. id must be the account record GUID returned by wpe_accounts_list; userName is not accepted.")]
    public static Task<string> AccountGet(WpeGatewayClient gateway, string id, CancellationToken cancellationToken = default) => gateway.InvokeAsync("accounts.get", new AccountGetInput(id), cancellationToken);
    [McpServerTool(Name = "wpe_account_logins_list"), Description("List an account's native login-location records. id must be the account record GUID returned by wpe_accounts_list; this is not a device inventory.")]
    public static Task<string> AccountLoginsList(WpeGatewayClient gateway, string id, int? limit = null, string? cursor = null, CancellationToken cancellationToken = default) => gateway.InvokeAsync("accounts.logins.list", new AccountLoginsListInput(id, limit, cursor), cancellationToken);
    [McpServerTool(Name = "wpe_firewall_get"), Description("Return WPE firewall configuration without modifying it.")]
    public static Task<string> FirewallGet(WpeGatewayClient gateway, CancellationToken cancellationToken) => gateway.InvokeAsync("firewall.get", null, cancellationToken);
    [McpServerTool(Name = "wpe_proxy_settings_get"), Description("Return proxy settings, limits, and configured external-proxy credentials without modifying WPE.")]
    public static Task<string> ProxySettingsGet(WpeGatewayClient gateway, CancellationToken cancellationToken) => gateway.InvokeAsync("proxy.settings.get", null, cancellationToken);
    [McpServerTool(Name = "wpe_proxy_config_get"), Description("Return the complete proxy configuration snapshot, including configured external-proxy credentials.")]
    public static Task<string> ProxyConfigGet(WpeGatewayClient gateway, CancellationToken cancellationToken) => gateway.InvokeAsync("proxy.config.get", null, cancellationToken);
    [McpServerTool(Name = "wpe_proxy_runtime_get"), Description("Return live proxy runtime diagnostics: listener configuration, running state, and connection counts. Nothing is modified.")]
    public static Task<string> ProxyRuntimeGet(WpeGatewayClient gateway, CancellationToken cancellationToken) => gateway.InvokeAsync("proxy.runtime.get", null, cancellationToken);
    [McpServerTool(Name = "wpe_remote_management_get"), Description("Return WPE remote-management configuration, including the administrator credentials and whether its HTTP server is running.")]
    public static Task<string> RemoteManagementGet(WpeGatewayClient gateway, CancellationToken cancellationToken = default) => gateway.InvokeAsync("remoteManagement.get", null, cancellationToken);
    [McpServerTool(Name = "wpe_remote_management_save"), Description("Save WPE remote-management address and administrator credentials, then start or stop its existing HTTP server according to enabled.")]
    public static Task<string> RemoteManagementSave(WpeGatewayClient gateway, bool enabled, string ip, int port, string userName, string password, string idempotencyKey, CancellationToken cancellationToken = default) => gateway.InvokeAsync("remoteManagement.save", new RemoteManagementSaveInput(enabled, ip, port, userName, password, idempotencyKey), cancellationToken);
    [McpServerTool(Name = "wpe_setting_get"), Description("Return the complete configuration snapshot for one WPE settings page. page is proxy, process, leach, hook, list, map, extproxy, hotkey, remote, firewall, system, or log; mode is proxy or inject where applicable. Backup has no readable settings page; use wpe_export or wpe_import directly.")]
    public static Task<string> SettingGet(WpeGatewayClient gateway, string page, string? mode = null, CancellationToken cancellationToken = default) => gateway.InvokeAsync("settings.get", new SettingGetInput(page, mode), cancellationToken);
    [McpServerTool(Name = "wpe_setting_save"), Description("Save one WPE settings page using its complete current-page values. First call wpe_setting_get for the same page, then submit that returned object with only intentional edits: do not invent values or omitted fields. page is proxy, list, map, extproxy, hotkey, remote, firewall, system, or log; use the specialized process/leach/hook/backup tools for those native workflows.")]
    public static Task<string> SettingSave(WpeGatewayClient gateway, string page, JsonElement values, string idempotencyKey, CancellationToken cancellationToken = default) => gateway.InvokeAsync("settings.save", new SettingSaveInput(page, values, idempotencyKey), cancellationToken);
    [McpServerTool(Name = "wpe_map_local_save"), Description("Create or update one WPE local HTTP mapping rule. id is the returned mapping GUID, or an empty string to create; protocol is 0 for HTTP or 1 for HTTPS.")]
    public static Task<string> MapLocalSave(WpeGatewayClient gateway, string id, int protocol, string host, int port, string remotePath, string localPath, string idempotencyKey, CancellationToken cancellationToken = default) => gateway.InvokeAsync("map.local.save", new MapLocalSaveInput(id, protocol, host, port, remotePath, localPath, idempotencyKey), cancellationToken);
    [McpServerTool(Name = "wpe_map_remote_save"), Description("Create or update one WPE remote HTTP mapping rule. id is the returned mapping GUID, or an empty string to create; protocolFrom and protocolTo are each 0 for HTTP or 1 for HTTPS.")]
    public static Task<string> MapRemoteSave(WpeGatewayClient gateway, string id, int protocolFrom, string hostFrom, int portFrom, string pathFrom, int protocolTo, string hostTo, int portTo, string pathTo, string idempotencyKey, CancellationToken cancellationToken = default) => gateway.InvokeAsync("map.remote.save", new MapRemoteSaveInput(id, protocolFrom, hostFrom, portFrom, pathFrom, protocolTo, hostTo, portTo, pathTo, idempotencyKey), cancellationToken);
    [McpServerTool(Name = "wpe_wpc_servers_list"), Description("List WPE ProxyCap (WPC) server configurations and their rule counts.")]
    public static Task<string> WpcServersList(WpeGatewayClient gateway, CancellationToken cancellationToken = default) => gateway.InvokeAsync("wpc.servers.list", null, cancellationToken);
    [McpServerTool(Name = "wpe_wpc_server_save"), Description("Create or update one WPE ProxyCap (WPC) server, including its three client URL fields. To create, omit id entirely; the result returns the generated GUID. To update, id accepts the exact visible server name or GUID.")]
    public static Task<string> WpcServerSave(WpeGatewayClient gateway, bool enabled, string name, string ip, int port, string forgotUrl, string registerUrl, string verifyUrl, string idempotencyKey, string? id = null, CancellationToken cancellationToken = default) => gateway.InvokeAsync("wpc.server.save", new WpcServerSaveInput(id, enabled, name, ip, port, forgotUrl, registerUrl, verifyUrl, idempotencyKey), cancellationToken);
    [McpServerTool(Name = "wpe_wpc_server_rules_list"), Description("List proxy rules under one WPC server. serverId accepts its exact server name or GUID.")]
    public static Task<string> WpcServerRulesList(WpeGatewayClient gateway, string serverId, CancellationToken cancellationToken = default) => gateway.InvokeAsync("wpc.server.rules.list", new WpcServerRulesListInput(serverId), cancellationToken);
    [McpServerTool(Name = "wpe_wpc_server_rule_save"), Description("Create or update one proxy rule under a WPE ProxyCap (WPC) server. serverId accepts the exact visible server name or GUID. To create a rule, omit id; to update, use the rule GUID returned by wpe_wpc_server_rules_list. type is the native RuleType numeric value 0=DOMAIN, 1=DOMAIN-SUFFIX, 2=DOMAIN-KEYWORD, 3=DOMAIN-REGEX, 4=GEOIP, 5=GEOSITE, 6=IP-CIDR, 7=IP-CIDR6, 8=SRC-IP-CIDR, 9=SRC-PORT, 10=DST-PORT, 11=PROCESS-NAME, 12=PROCESS-PATH, 13=NETWORK, 14=RULE-SET, 15=MATCH, 16=AND, 17=OR, 18=NOT, 19=SUB-RULE, 20=IN-PORT, 21=UI-EX, 22=COMMAND, 23=DEVICE-NAME; action is 0=PROXY, 1=REJECT, or 2=DIRECT. A global proxy rule is enabled MATCH (type 15), empty argument, PROXY (action 0).")]
    public static Task<string> WpcServerRuleSave(WpeGatewayClient gateway, string serverId, bool enabled, int type, string argument, int action, string idempotencyKey, string? id = null, CancellationToken cancellationToken = default) => gateway.InvokeAsync("wpc.server.rule.save", new WpcServerRuleSaveInput(serverId, id, enabled, type, argument, action, idempotencyKey), cancellationToken);
    [McpServerTool(Name = "wpe_connections_summary_get"), Description("Return complete connection counts grouped by protocol and WPC-control versus ordinary sessions.")]
    public static Task<string> ConnectionsSummaryGet(WpeGatewayClient gateway, CancellationToken cancellationToken) => gateway.InvokeAsync("connections.summary.get", null, cancellationToken);
    [McpServerTool(Name = "wpe_proxy_bind_ip_set"), Description("Request a reversible proxy listening-address change. WPE validates an explicit IPv4/IPv6 address or automatic detection, then persists after local confirmation.")]
    public static Task<string> ProxyBindIpSet(WpeGatewayClient gateway, bool auto, string ip, string idempotencyKey, CancellationToken cancellationToken = default) => gateway.InvokeAsync("proxy.bindIp.set", new ProxyBindIpSetInput(auto, ip, idempotencyKey), cancellationToken);
    [McpServerTool(Name = "wpe_external_proxy_set_enabled"), Description("Request a reversible external-proxy enable/disable change. WPE validates the configured endpoint and persists after local confirmation.")]
    public static Task<string> ExternalProxySetEnabled(WpeGatewayClient gateway, bool enabled, string idempotencyKey, CancellationToken cancellationToken = default) => gateway.InvokeAsync("proxy.external.setEnabled", new ExternalProxySetEnabledInput(enabled, idempotencyKey), cancellationToken);
    [McpServerTool(Name = "wpe_proxy_start"), Description("Request starting WPE proxy listeners. This may bind configured ports and requires local confirmation.")]
    public static Task<string> ProxyStart(WpeGatewayClient gateway, string idempotencyKey, CancellationToken cancellationToken = default) => gateway.InvokeAsync("proxy.start", new ProxyLifecycleInput(idempotencyKey), cancellationToken);
    [McpServerTool(Name = "wpe_proxy_stop"), Description("Request stopping WPE proxy listeners. Existing proxy connections may be disconnected; local confirmation is required.")]
    public static Task<string> ProxyStop(WpeGatewayClient gateway, string idempotencyKey, CancellationToken cancellationToken = default) => gateway.InvokeAsync("proxy.stop", new ProxyLifecycleInput(idempotencyKey), cancellationToken);
    [McpServerTool(Name = "wpe_executors_stop_all"), Description("Request stopping all active WPE sender and robot executors. This never starts tasks or sends packets; it follows the global MCP confirmation setting.")]
    public static Task<string> ExecutorsStopAll(WpeGatewayClient gateway, string idempotencyKey, CancellationToken cancellationToken = default) => gateway.InvokeAsync("executors.stopAll", new ExecutorStopAllInput(idempotencyKey), cancellationToken);
    [McpServerTool(Name = "wpe_capture_clear"), Description("Clear one WPE capture list after local confirmation. list must be proxy or packet (packet is the inject capture list).")]
    public static Task<string> CaptureClear(WpeGatewayClient gateway, string list, string idempotencyKey, CancellationToken cancellationToken = default) => gateway.InvokeAsync("capture.clear", new CaptureListInput(list, idempotencyKey), cancellationToken);
    [McpServerTool(Name = "wpe_import"), Description("The single import entry point for every native WPE format, using its original open-file dialog and any required decryption-password dialog. kind is backup, filters, accounts, firewallWhiteList, firewallBlackList, mapLocal, mapRemote, sends, robots, sendCollection, warehouses, warehouseStores, or autoStores. fileName optionally pre-fills the native open dialog. sendId for sendCollection and warehouseId for warehouseStores each accept the exact visible name or GUID. Backup import reloads imported configuration into the active WPE UI.")]
    public static Task<string> Import(WpeGatewayClient gateway, string kind, string idempotencyKey, string? fileName = null, string? sendId = null, string? warehouseId = null, CancellationToken cancellationToken = default) => gateway.InvokeAsync("import.run", new ImportInput(kind, idempotencyKey, fileName, sendId, warehouseId), cancellationToken);
    [McpServerTool(Name = "wpe_export"), Description("The single export entry point for every native WPE format, using its original save dialog. kind is backup, capture, filters, certificate, accounts, accountsSelected, firewallWhiteList, firewallBlackList, mapLocal, mapRemote, sends, robots, sendCollection, warehouses, warehouseStores, autoStores, logs, or extraction. fileName pre-fills the native dialog. backupParts selects backup modules (all=true exports every module); captureList and capturePacketIds select captured packets. certificateType selects CER/CRT/PEM/Android, logKind selects system/filter/proxy/mcp, and sendId or warehouseId accepts an exact visible name or GUID where required.")]
    public static Task<string> Export(WpeGatewayClient gateway, string kind, string idempotencyKey, string? fileName = null, JsonElement? backupParts = null, string? captureList = null, long[]? capturePacketIds = null, int? certificateType = null, string? logKind = null, string? sendId = null, string? warehouseId = null, string[]? ids = null, int? extractionKind = null, string? extractionText = null, CancellationToken cancellationToken = default) => gateway.InvokeAsync("export.run", new ExportInput(kind, idempotencyKey, fileName, backupParts, captureList, capturePacketIds, certificateType, logKind, sendId, warehouseId, ids, extractionKind, extractionText), cancellationToken);
    [McpServerTool(Name = "wpe_sends_start"), Description("Start WPE's enabled send-task list after local confirmation. This may send packets.")]
    public static Task<string> SendsStart(WpeGatewayClient gateway, string idempotencyKey, CancellationToken cancellationToken = default) => gateway.InvokeAsync("sends.start", new ExecutorStopAllInput(idempotencyKey), cancellationToken);
    [McpServerTool(Name = "wpe_sends_stop"), Description("Stop WPE's send-task list after local confirmation.")]
    public static Task<string> SendsStop(WpeGatewayClient gateway, string idempotencyKey, CancellationToken cancellationToken = default) => gateway.InvokeAsync("sends.stop", new ExecutorStopAllInput(idempotencyKey), cancellationToken);
    [McpServerTool(Name = "wpe_send_start"), Description("Start one enabled WPE send task after local confirmation. id accepts its exact visible name or GUID. This may send packets.")]
    public static Task<string> SendStart(WpeGatewayClient gateway, string id, string idempotencyKey, CancellationToken cancellationToken = default) => gateway.InvokeAsync("send.start", new EntityWriteInput(id, idempotencyKey), cancellationToken);
    [McpServerTool(Name = "wpe_robots_start"), Description("Start WPE's enabled robot-task list after local confirmation.")]
    public static Task<string> RobotsStart(WpeGatewayClient gateway, string idempotencyKey, CancellationToken cancellationToken = default) => gateway.InvokeAsync("robots.start", new ExecutorStopAllInput(idempotencyKey), cancellationToken);
    [McpServerTool(Name = "wpe_robots_stop"), Description("Stop WPE's robot-task list after local confirmation.")]
    public static Task<string> RobotsStop(WpeGatewayClient gateway, string idempotencyKey, CancellationToken cancellationToken = default) => gateway.InvokeAsync("robots.stop", new ExecutorStopAllInput(idempotencyKey), cancellationToken);
    [McpServerTool(Name = "wpe_robot_start"), Description("Start one enabled WPE robot task after local confirmation. id accepts its exact visible name or GUID.")]
    public static Task<string> RobotStart(WpeGatewayClient gateway, string id, string idempotencyKey, CancellationToken cancellationToken = default) => gateway.InvokeAsync("robot.start", new EntityWriteInput(id, idempotencyKey), cancellationToken);
    [McpServerTool(Name = "wpe_inject_attach"), Description("Attach WPE to an existing target process, or start and inject an executable, after local confirmation. Supply pid for an existing process, or path (and optional args) to start one; method is the optional native injection-method numeric value returned by the current WPE injection settings.")]
    public static Task<string> InjectAttach(WpeGatewayClient gateway, int pid, string? path, string? args, int? method, string idempotencyKey, CancellationToken cancellationToken = default) => gateway.InvokeAsync("inject.attach", new InjectAttachInput(pid, path, args, method, idempotencyKey), cancellationToken);
    [McpServerTool(Name = "wpe_inject_quick_attach"), Description("Repeat WPE's existing quick-inject action using its saved last-injection record after local confirmation.")]
    public static Task<string> InjectQuickAttach(WpeGatewayClient gateway, string idempotencyKey, CancellationToken cancellationToken = default) => gateway.InvokeAsync("inject.quickAttach", new ExecutorStopAllInput(idempotencyKey), cancellationToken);
    [McpServerTool(Name = "wpe_inject_detach"), Description("Detach WPE from the current injected target after local confirmation.")]
    public static Task<string> InjectDetach(WpeGatewayClient gateway, string idempotencyKey, CancellationToken cancellationToken = default) => gateway.InvokeAsync("inject.detach", new ExecutorStopAllInput(idempotencyKey), cancellationToken);
    [McpServerTool(Name = "wpe_inject_start_hook"), Description("Start WPE's existing hook in the current injected target after local confirmation.")]
    public static Task<string> InjectStartHook(WpeGatewayClient gateway, string idempotencyKey, CancellationToken cancellationToken = default) => gateway.InvokeAsync("inject.startHook", new ExecutorStopAllInput(idempotencyKey), cancellationToken);
    [McpServerTool(Name = "wpe_inject_stop_hook"), Description("Stop WPE's existing hook in the current injected target after local confirmation.")]
    public static Task<string> InjectStopHook(WpeGatewayClient gateway, string idempotencyKey, CancellationToken cancellationToken = default) => gateway.InvokeAsync("inject.stopHook", new ExecutorStopAllInput(idempotencyKey), cancellationToken);
    [McpServerTool(Name = "wpe_driver_uninstall"), Description("Run WPE's existing driver-uninstall dialog after local confirmation. The native operation may require a restart.")]
    public static Task<string> DriverUninstall(WpeGatewayClient gateway, string idempotencyKey, CancellationToken cancellationToken = default) => gateway.InvokeAsync("driver.uninstall", new ExecutorStopAllInput(idempotencyKey), cancellationToken);
    [McpServerTool(Name = "wpe_process_proxy_save"), Description("Save WPE's existing process-proxy settings after local confirmation; the native workflow installs/configures the selected driver when needed. First call wpe_setting_get with page process, then submit its complete values with only intentional edits; do not guess driverType or dependent fields.")]
    public static Task<string> ProcessProxySave(WpeGatewayClient gateway, int driverType, bool mustTcp, string? ip, int port, bool appointPort, string? appointPortContent, bool auth, string? userName, string? passWord, int[]? pids, string idempotencyKey, CancellationToken cancellationToken = default) => gateway.InvokeAsync("processProxy.save", new ProcessProxySaveInput(driverType, mustTcp, ip, port, appointPort, appointPortContent, auth, userName, passWord, pids, idempotencyKey), cancellationToken);
    [McpServerTool(Name = "wpe_packet_edit_send_start"), Description("Start WPE's existing packet-editor send session after local confirmation. list must be proxy or packet; obtain id, socket, and payloadBase64 from wpe_packet_edit_get rather than guessing them.")]
    public static Task<string> PacketEditSendStart(WpeGatewayClient gateway, string list, long id, int socket, string payloadBase64, bool continuous, int times, int interval, bool progression, int position, int step, bool carry, int carryCount, string idempotencyKey, CancellationToken cancellationToken = default) => gateway.InvokeAsync("packetEdit.sendStart", new PacketEditSendInput(list, id, socket, payloadBase64, continuous, times, interval, progression, position, step, carry, carryCount, idempotencyKey), cancellationToken);
    [McpServerTool(Name = "wpe_packet_edit_send_stop"), Description("Stop WPE's current packet-editor send session after local confirmation.")]
    public static Task<string> PacketEditSendStop(WpeGatewayClient gateway, string idempotencyKey, CancellationToken cancellationToken = default) => gateway.InvokeAsync("packetEdit.sendStop", new ExecutorStopAllInput(idempotencyKey), cancellationToken);
    [McpServerTool(Name = "wpe_start_mode_select"), Description("Select WPE proxy or inject mode only while WPE is on its start page; success opens that mode's page. This never starts proxy listeners or injects. If the requested mode is already selected, it returns an unchanged successful state; a different selected mode returns a structured unavailable state.")]
    public static Task<string> StartModeSelect(WpeGatewayClient gateway, string mode, string idempotencyKey, CancellationToken cancellationToken = default) => gateway.InvokeAsync("start.mode.select", new StartModeSelectInput(mode, idempotencyKey), cancellationToken);
    [McpServerTool(Name = "wpe_firewall_rules_list"), Description("List a bounded page of WPE firewall rules. list must be white or black.")]
    public static Task<string> FirewallRulesList(WpeGatewayClient gateway, string list, int? limit = null, string? cursor = null, CancellationToken cancellationToken = default) => gateway.InvokeAsync("firewall.rules.list", new FirewallRulesListInput(list, limit, cursor), cancellationToken);
    [McpServerTool(Name = "wpe_firewall_rule_add"), Description("Request addition of one WPE firewall rule. list must be white or black. WPE validates the address and, if expiryEnabled is true, requires a future ISO-8601 expiryTime before confirmation and persistence.")]
    public static Task<string> FirewallRuleAdd(WpeGatewayClient gateway, string list, string address, string idempotencyKey, bool expiryEnabled = false, string? expiryTime = null, CancellationToken cancellationToken = default) => gateway.InvokeAsync("firewall.rule.add", new FirewallRuleAddInput(list, address, idempotencyKey, expiryEnabled, expiryTime), cancellationToken);
    [McpServerTool(Name = "wpe_firewall_rule_remove"), Description("Request removal of one exact WPE firewall rule. list must be white or black; address must exactly match a row returned by wpe_firewall_rules_list. WPE must show and receive a local confirmation before it applies.")]
    public static Task<string> FirewallRuleRemove(WpeGatewayClient gateway, string list, string address, string idempotencyKey, CancellationToken cancellationToken = default) => gateway.InvokeAsync("firewall.rule.remove", new FirewallRuleRemoveInput(list, address, idempotencyKey), cancellationToken);
    [McpServerTool(Name = "wpe_bytes_transcode"), Description("Convert caller-supplied bytes using WPE's encoding rules.")]
    public static Task<string> BytesTranscode(WpeGatewayClient gateway, string text, bool decode, CancellationToken cancellationToken = default) => gateway.InvokeAsync("bytes.transcode", new BytesTranscodeInput(text, decode), cancellationToken);
    [McpServerTool(Name = "wpe_bytes_compare"), Description("Compare two caller-supplied byte strings using WPE logic.")]
    public static Task<string> BytesCompare(WpeGatewayClient gateway, string left, string right, int minimumRun = 2, CancellationToken cancellationToken = default) => gateway.InvokeAsync("bytes.compare", new BytesCompareInput(left, right, minimumRun), cancellationToken);
    [McpServerTool(Name = "wpe_bytes_extract"), Description("Extract structured values from caller-supplied Base64 bytes using WPE logic. kind is a native extraction-format value from 0 through 32; obtain the intended format from the WPE extraction UI rather than guessing a numeric kind.")]
    public static Task<string> BytesExtract(WpeGatewayClient gateway, int kind, string contentBase64, CancellationToken cancellationToken = default) => gateway.InvokeAsync("bytes.extract", new BytesExtractInput(kind, contentBase64), cancellationToken);
    [McpServerTool(Name = "wpe_sends_list"), Description("List a bounded page of send-task metadata.")]
    public static Task<string> SendsList(WpeGatewayClient gateway, int? limit = null, string? cursor = null, CancellationToken cancellationToken = default) => gateway.InvokeAsync("sends.list", new PageInput(limit, cursor), cancellationToken);
    [McpServerTool(Name = "wpe_send_get"), Description("Get one send task's editable configuration. id accepts its exact visible name or GUID.")]
    public static Task<string> SendGet(WpeGatewayClient gateway, string id, CancellationToken cancellationToken = default) => gateway.InvokeAsync("sends.get", new EntityGetInput(id), cancellationToken);
    [McpServerTool(Name = "wpe_send_collection_list"), Description("List a bounded page of one send task's packet collection with its native preview fields. id accepts its exact visible name or GUID.")]
    public static Task<string> SendCollectionList(WpeGatewayClient gateway, string id, int? limit = null, string? cursor = null, CancellationToken cancellationToken = default) => gateway.InvokeAsync("sends.collection.list", new EntityPageInput(id, limit, cursor), cancellationToken);
    [McpServerTool(Name = "wpe_robots_list"), Description("List a bounded page of robot-task metadata.")]
    public static Task<string> RobotsList(WpeGatewayClient gateway, int? limit = null, string? cursor = null, CancellationToken cancellationToken = default) => gateway.InvokeAsync("robots.list", new PageInput(limit, cursor), cancellationToken);
    [McpServerTool(Name = "wpe_robot_get"), Description("Get one robot task and its native instruction configuration. id accepts its exact visible name or GUID.")]
    public static Task<string> RobotGet(WpeGatewayClient gateway, string id, CancellationToken cancellationToken = default) => gateway.InvokeAsync("robots.get", new EntityGetInput(id), cancellationToken);
    [McpServerTool(Name = "wpe_warehouse_list"), Description("List a bounded page of warehouse metadata.")]
    public static Task<string> WarehousesList(WpeGatewayClient gateway, int? limit = null, string? cursor = null, CancellationToken cancellationToken = default) => gateway.InvokeAsync("warehouses.list", new PageInput(limit, cursor), cancellationToken);
    [McpServerTool(Name = "wpe_warehouse_get"), Description("Get one warehouse and a bounded page of its stored-packet records. REQUIRED: first call wpe_warehouse_list, then pass that row's Id GUID as id. Do not omit id and do not use the warehouse display name.")]
    public static Task<string> WarehouseGet(WpeGatewayClient gateway, string id, int? limit = null, string? cursor = null, CancellationToken cancellationToken = default) => gateway.InvokeAsync("warehouses.get", new EntityPageInput(id, limit, cursor), cancellationToken);
    [McpServerTool(Name = "wpe_send_collection_action"), Description("Edit selected packets in one send collection after local confirmation. action must be top, up, down, bottom, copy, or delete. sendId accepts its exact visible send-task name or GUID. packetIds must be IDs returned by wpe_send_collection_list. This edits and persists the send task but never starts it.")]
    public static Task<string> SendCollectionAction(WpeGatewayClient gateway, string sendId, string[] packetIds, string action, string idempotencyKey, CancellationToken cancellationToken = default) => gateway.InvokeAsync("sends.collection.action", new SendCollectionActionInput(sendId, packetIds, action, idempotencyKey), cancellationToken);
    [McpServerTool(Name = "wpe_send_collection_clear"), Description("Clear one send task's packet collection after local confirmation. sendId accepts its exact visible name or GUID. This never starts the sender.")]
    public static Task<string> SendCollectionClear(WpeGatewayClient gateway, string sendId, string idempotencyKey, CancellationToken cancellationToken = default) => gateway.InvokeAsync("sends.collection.clear", new EntityWriteInput(sendId, idempotencyKey), cancellationToken);
    [McpServerTool(Name = "wpe_robot_instruction_add"), Description("Add one validated native robot instruction after local confirmation. robot accepts the exact visible robot name (for example, \"机器人 1\") or its GUID; WPE resolves a unique name internally and reports missing or duplicate names. type values are 0=send task GUID, 1=delay, 2=loop start, 3=loop end, 4=keyboard, 5=mouse, 6=send-packet list, 7=system socket, 8=switch. content is only that instruction's parameter—never prefix it with type or a localized name. For a fixed 1000 ms delay call type=1 and content=\"1000\"; a random delay is \"min-max\" such as \"500-1000\".")]
    public static Task<string> RobotInstructionAdd(WpeGatewayClient gateway, string robot, int type, string content, int insertAt, string idempotencyKey, CancellationToken cancellationToken = default) => gateway.InvokeAsync("robots.instructions.add", new RobotInstructionAddInput(robot, type, content, insertAt, idempotencyKey), cancellationToken);
    [McpServerTool(Name = "wpe_robot_instructions_save"), Description("Replace a robot's complete instruction list atomically after local confirmation. Use this for loops because WPE rejects a temporarily unmatched loop start/end. robot accepts its exact visible name or GUID. instructions is an ordered array of native instruction objects: delay uses type 1 with content milliseconds (or min-max); loop start uses type 2 with positive count content; loop end uses type 3 with empty content; keyboard uses type 4 with content action|key, where action is Press, Down, Up, Combine, or Text and the number-row 1 key is Press|D1. Read wpe_robot_get afterwards to verify the saved order.")]
    public static Task<string> RobotInstructionsSave(WpeGatewayClient gateway, string robot, JsonElement instructions, string idempotencyKey, CancellationToken cancellationToken = default) => gateway.InvokeAsync("robots.instructions.save", new RobotInstructionsSaveInput(robot, instructions, idempotencyKey), cancellationToken);
    [McpServerTool(Name = "wpe_robot_instruction_action"), Description("Edit native robot instructions after local confirmation. action must be top, up, down, bottom, delete, or clear (copy is not supported). robotId accepts the exact visible robot name or GUID; indexes are zero-based positions in the current wpe_robot_get instruction array, and may be empty only for clear.")]
    public static Task<string> RobotInstructionAction(WpeGatewayClient gateway, string robotId, int[] indexes, string action, string idempotencyKey, CancellationToken cancellationToken = default) => gateway.InvokeAsync("robots.instructions.action", new RobotInstructionActionInput(robotId, indexes, action, idempotencyKey), cancellationToken);
    [McpServerTool(Name = "wpe_auto_stores_list"), Description("List automatic warehouse rules without changing them.")]
    public static Task<string> AutoStoresList(WpeGatewayClient gateway, CancellationToken cancellationToken = default) => gateway.InvokeAsync("autoStores.list", null, cancellationToken);
    [McpServerTool(Name = "wpe_auto_stores_save"), Description("Create or update one automatic warehouse rule after local confirmation. An empty id creates a disabled rule; warehouseId accepts its exact visible warehouse name or GUID.")]
    public static Task<string> AutoStoresSave(WpeGatewayClient gateway, string? id, string packetHead, string warehouseId, string idempotencyKey, CancellationToken cancellationToken = default) => gateway.InvokeAsync("autoStores.save", new AutoStoresSaveInput(id, packetHead, warehouseId, idempotencyKey), cancellationToken);
    [McpServerTool(Name = "wpe_auto_stores_set_enabled"), Description("Enable or disable one automatic warehouse rule after local confirmation.")]
    public static Task<string> AutoStoresSetEnabled(WpeGatewayClient gateway, string id, bool enabled, string idempotencyKey, CancellationToken cancellationToken = default) => gateway.InvokeAsync("autoStores.setEnabled", new EntityEnabledInput(id, enabled, idempotencyKey), cancellationToken);
    [McpServerTool(Name = "wpe_auto_stores_delete"), Description("Delete one automatic warehouse rule after local confirmation.")]
    public static Task<string> AutoStoresDelete(WpeGatewayClient gateway, string id, string idempotencyKey, CancellationToken cancellationToken = default) => gateway.InvokeAsync("autoStores.delete", new EntityWriteInput(id, idempotencyKey), cancellationToken);
    [McpServerTool(Name = "wpe_warehouse_stores_action"), Description("Edit selected warehouse packets after local confirmation. action must be top, up, down, bottom, copy, export, or delete. warehouseId accepts its exact visible name or GUID; storeIds must be IDs returned by wpe_warehouse_get. Export opens WPE's local save dialog.")]
    public static Task<string> WarehouseStoresAction(WpeGatewayClient gateway, string warehouseId, string[] storeIds, string action, string idempotencyKey, CancellationToken cancellationToken = default) => gateway.InvokeAsync("warehouses.stores.action", new WarehouseStoresActionInput(warehouseId, storeIds, action, idempotencyKey), cancellationToken);
    [McpServerTool(Name = "wpe_warehouse_stores_command"), Description("Run a native warehouse command after local confirmation. action must be import, export, or clear. warehouseId accepts its exact visible name or GUID. Import/export open WPE's local file dialogs.")]
    public static Task<string> WarehouseStoresCommand(WpeGatewayClient gateway, string warehouseId, string action, string idempotencyKey, CancellationToken cancellationToken = default) => gateway.InvokeAsync("warehouses.stores.command", new WarehouseCommandInput(warehouseId, action, idempotencyKey), cancellationToken);
    [McpServerTool(Name = "wpe_packet_edit_get"), Description("Get one captured packet for editing. list must be proxy or packet (packet is the inject capture list). Payload is returned as Base64 only for this explicit request.")]
    public static Task<string> PacketEditGet(WpeGatewayClient gateway, string list, long id, CancellationToken cancellationToken = default) => gateway.InvokeAsync("packet.edit.get", new PacketEditGetInput(list, id), cancellationToken);
    [McpServerTool(Name = "wpe_packet_edit_save"), Description("Replace one captured packet's socket and payload after local confirmation. list must be proxy or packet. First call wpe_packet_edit_get and reuse its id, socket, and payloadBase64 except for the intended edit.")]
    public static Task<string> PacketEditSave(WpeGatewayClient gateway, string list, long id, int socket, string payloadBase64, string idempotencyKey, CancellationToken cancellationToken = default) => gateway.InvokeAsync("packet.edit.save", new PacketEditSaveInput(list, id, socket, payloadBase64, idempotencyKey), cancellationToken);
    [McpServerTool(Name = "wpe_packet_edit_add_to_send"), Description("Copy one captured packet, using supplied Base64 bytes, into a send task after local confirmation. list must be proxy or packet; obtain the packet fields from wpe_packet_edit_get. sendId accepts its exact visible name or GUID. It never starts the sender.")]
    public static Task<string> PacketEditAddToSend(WpeGatewayClient gateway, string sendId, string list, long id, string payloadBase64, string idempotencyKey, CancellationToken cancellationToken = default) => gateway.InvokeAsync("packet.edit.addToSend", new PacketEditAddToSendInput(sendId, list, id, payloadBase64, idempotencyKey), cancellationToken);
    [McpServerTool(Name = "wpe_send_set_enabled"), Description("Enable or disable one existing WPE send task after local confirmation. id accepts its exact visible name or GUID. This never starts the sender.")]
    public static Task<string> SendSetEnabled(WpeGatewayClient gateway, string id, bool enabled, string idempotencyKey, CancellationToken cancellationToken = default) => gateway.InvokeAsync("sends.setEnabled", new EntityEnabledInput(id, enabled, idempotencyKey), cancellationToken);
    [McpServerTool(Name = "wpe_robot_set_enabled"), Description("Enable or disable one existing WPE robot task after local confirmation. id accepts its exact visible name or GUID. This never starts the robot.")]
    public static Task<string> RobotSetEnabled(WpeGatewayClient gateway, string id, bool enabled, string idempotencyKey, CancellationToken cancellationToken = default) => gateway.InvokeAsync("robots.setEnabled", new EntityEnabledInput(id, enabled, idempotencyKey), cancellationToken);
    [McpServerTool(Name = "wpe_send_create"), Description("Create one empty WPE send task after local confirmation. This creates a task only; it never sends packets.")]
    public static Task<string> SendCreate(WpeGatewayClient gateway, string idempotencyKey, CancellationToken cancellationToken = default) => gateway.InvokeAsync("tasks.create", new TaskCreateInput("send", idempotencyKey), cancellationToken);
    [McpServerTool(Name = "wpe_robot_create"), Description("Create one empty WPE robot task after local confirmation. This creates a robot only; it never executes it.")]
    public static Task<string> RobotCreate(WpeGatewayClient gateway, string idempotencyKey, CancellationToken cancellationToken = default) => gateway.InvokeAsync("tasks.create", new TaskCreateInput("robot", idempotencyKey), cancellationToken);
    [McpServerTool(Name = "wpe_warehouse_create"), Description("Create one empty WPE warehouse after local confirmation. This creates storage only; it does not import or alter captured packets.")]
    public static Task<string> WarehouseCreate(WpeGatewayClient gateway, string idempotencyKey, CancellationToken cancellationToken = default) => gateway.InvokeAsync("tasks.create", new TaskCreateInput("warehouse", idempotencyKey), cancellationToken);
    private static Task<string> TaskUpdate(WpeGatewayClient gateway, string kind, string id, string name, string idempotencyKey, bool? useSystemSocket = null, int? loopCount = null, int? loopInterval = null, string? notes = null, CancellationToken cancellationToken = default) =>
        gateway.InvokeAsync("tasks.update", new TaskUpdateInput(kind, id, name, idempotencyKey, useSystemSocket, loopCount, loopInterval, notes), cancellationToken);
    [McpServerTool(Name = "wpe_send_update"), Description("Update one existing WPE send task by GUID. Omitted scheduling values retain their current values; this never starts sending.")]
    public static Task<string> SendUpdate(WpeGatewayClient gateway, string id, string name, string idempotencyKey, bool? useSystemSocket = null, int? loopCount = null, int? loopInterval = null, string? notes = null, CancellationToken cancellationToken = default) => TaskUpdate(gateway, "send", id, name, idempotencyKey, useSystemSocket, loopCount, loopInterval, notes, cancellationToken);
    [McpServerTool(Name = "wpe_robot_update"), Description("Update one existing WPE robot task by GUID. This never starts the robot.")]
    public static Task<string> RobotUpdate(WpeGatewayClient gateway, string id, string name, string idempotencyKey, CancellationToken cancellationToken = default) => TaskUpdate(gateway, "robot", id, name, idempotencyKey, cancellationToken: cancellationToken);
    [McpServerTool(Name = "wpe_warehouse_update"), Description("Update one existing WPE warehouse name by GUID.")]
    public static Task<string> WarehouseUpdate(WpeGatewayClient gateway, string id, string name, string idempotencyKey, CancellationToken cancellationToken = default) => TaskUpdate(gateway, "warehouse", id, name, idempotencyKey, cancellationToken: cancellationToken);
    private static Task<string> TaskAction(WpeGatewayClient gateway, string operation, string kind, string[] ids, string direction, string idempotencyKey, CancellationToken cancellationToken = default) =>
        gateway.InvokeAsync(operation, new TaskActionInput(kind, ids, direction, idempotencyKey), cancellationToken);
    [McpServerTool(Name = "wpe_send_move"), Description("Move selected existing WPE send tasks by GUID. direction must be top, up, down, or bottom.")]
    public static Task<string> SendMove(WpeGatewayClient gateway, string[] ids, string direction, string idempotencyKey, CancellationToken cancellationToken = default) => TaskAction(gateway, "tasks.move", "send", ids, direction, idempotencyKey, cancellationToken);
    [McpServerTool(Name = "wpe_robot_move"), Description("Move selected existing WPE robot tasks by GUID. direction must be top, up, down, or bottom.")]
    public static Task<string> RobotMove(WpeGatewayClient gateway, string[] ids, string direction, string idempotencyKey, CancellationToken cancellationToken = default) => TaskAction(gateway, "tasks.move", "robot", ids, direction, idempotencyKey, cancellationToken);
    [McpServerTool(Name = "wpe_warehouse_move"), Description("Move selected existing WPE warehouses by GUID. direction must be top, up, down, or bottom.")]
    public static Task<string> WarehouseMove(WpeGatewayClient gateway, string[] ids, string direction, string idempotencyKey, CancellationToken cancellationToken = default) => TaskAction(gateway, "tasks.move", "warehouse", ids, direction, idempotencyKey, cancellationToken);
    [McpServerTool(Name = "wpe_send_copy"), Description("Copy selected existing WPE send tasks by GUID. This never starts sending.")]
    public static Task<string> SendCopy(WpeGatewayClient gateway, string[] ids, string idempotencyKey, CancellationToken cancellationToken = default) => TaskAction(gateway, "tasks.copy", "send", ids, "copy", idempotencyKey, cancellationToken);
    [McpServerTool(Name = "wpe_robot_copy"), Description("Copy selected existing WPE robot tasks by GUID. This never starts robots.")]
    public static Task<string> RobotCopy(WpeGatewayClient gateway, string[] ids, string idempotencyKey, CancellationToken cancellationToken = default) => TaskAction(gateway, "tasks.copy", "robot", ids, "copy", idempotencyKey, cancellationToken);
    [McpServerTool(Name = "wpe_warehouse_copy"), Description("Copy selected existing WPE warehouses by GUID.")]
    public static Task<string> WarehouseCopy(WpeGatewayClient gateway, string[] ids, string idempotencyKey, CancellationToken cancellationToken = default) => TaskAction(gateway, "tasks.copy", "warehouse", ids, "copy", idempotencyKey, cancellationToken);
    [McpServerTool(Name = "wpe_send_delete"), Description("Delete selected existing WPE send tasks by GUID after local confirmation. This never starts sending.")]
    public static Task<string> SendDelete(WpeGatewayClient gateway, string[] ids, string idempotencyKey, CancellationToken cancellationToken = default) => TaskAction(gateway, "tasks.delete", "send", ids, "delete", idempotencyKey, cancellationToken);
    [McpServerTool(Name = "wpe_robot_delete"), Description("Delete selected existing WPE robot tasks by GUID after local confirmation. This never starts robots.")]
    public static Task<string> RobotDelete(WpeGatewayClient gateway, string[] ids, string idempotencyKey, CancellationToken cancellationToken = default) => TaskAction(gateway, "tasks.delete", "robot", ids, "delete", idempotencyKey, cancellationToken);
    [McpServerTool(Name = "wpe_warehouse_delete"), Description("Delete selected existing WPE warehouses by GUID after local confirmation.")]
    public static Task<string> WarehouseDelete(WpeGatewayClient gateway, string[] ids, string idempotencyKey, CancellationToken cancellationToken = default) => TaskAction(gateway, "tasks.delete", "warehouse", ids, "delete", idempotencyKey, cancellationToken);
    private static Task<string> TaskClear(WpeGatewayClient gateway, string kind, string idempotencyKey, CancellationToken cancellationToken = default) =>
        gateway.InvokeAsync("tasks.clear", new TaskCreateInput(kind, idempotencyKey), cancellationToken);
    [McpServerTool(Name = "wpe_sends_clear"), Description("Clear all WPE send tasks after local confirmation. This never starts sending.")]
    public static Task<string> SendsClear(WpeGatewayClient gateway, string idempotencyKey, CancellationToken cancellationToken = default) => TaskClear(gateway, "send", idempotencyKey, cancellationToken);
    [McpServerTool(Name = "wpe_robots_clear"), Description("Clear all WPE robot tasks after local confirmation. This never starts robots.")]
    public static Task<string> RobotsClear(WpeGatewayClient gateway, string idempotencyKey, CancellationToken cancellationToken = default) => TaskClear(gateway, "robot", idempotencyKey, cancellationToken);
    [McpServerTool(Name = "wpe_warehouses_clear"), Description("Clear all WPE warehouses after local confirmation.")]
    public static Task<string> WarehousesClear(WpeGatewayClient gateway, string idempotencyKey, CancellationToken cancellationToken = default) => TaskClear(gateway, "warehouse", idempotencyKey, cancellationToken);
    [McpServerTool(Name = "wpe_capture_add_to_send"), Description("Copy selected inject-capture packets into an existing send task after local confirmation. sendId accepts its exact visible name or GUID. This never starts the sender.")]
    public static Task<string> CaptureAddToSend(WpeGatewayClient gateway, string sendId, long[] packetIds, string idempotencyKey, CancellationToken cancellationToken = default) => gateway.InvokeAsync("capture.addToSend", new CaptureAddInput(sendId, packetIds, idempotencyKey), cancellationToken);
    [McpServerTool(Name = "wpe_capture_add_to_warehouse"), Description("Copy selected inject-capture packets into an existing warehouse after local confirmation. warehouseId accepts its exact visible name or GUID.")]
    public static Task<string> CaptureAddToWarehouse(WpeGatewayClient gateway, string warehouseId, long[] packetIds, string idempotencyKey, CancellationToken cancellationToken = default) => gateway.InvokeAsync("capture.addToWarehouse", new CaptureAddInput(warehouseId, packetIds, idempotencyKey), cancellationToken);
    [McpServerTool(Name = "wpe_proxy_capture_add_to_send"), Description("Copy selected proxy-capture packets into an existing send task after local confirmation. sendId accepts its exact visible name or GUID. This never starts the sender.")]
    public static Task<string> ProxyCaptureAddToSend(WpeGatewayClient gateway, string sendId, long[] packetIds, string idempotencyKey, CancellationToken cancellationToken = default) => gateway.InvokeAsync("proxyCapture.addToSend", new CaptureAddInput(sendId, packetIds, idempotencyKey), cancellationToken);
    [McpServerTool(Name = "wpe_proxy_capture_add_to_warehouse"), Description("Copy selected proxy-capture packets into an existing warehouse after local confirmation. warehouseId accepts its exact visible name or GUID.")]
    public static Task<string> ProxyCaptureAddToWarehouse(WpeGatewayClient gateway, string warehouseId, long[] packetIds, string idempotencyKey, CancellationToken cancellationToken = default) => gateway.InvokeAsync("proxyCapture.addToWarehouse", new CaptureAddInput(warehouseId, packetIds, idempotencyKey), cancellationToken);
}

public sealed record PageInput(int? Limit = null, string? Cursor = null);
public sealed record AccountListInput(int? Limit = null, string? Cursor = null, string? UserName = null);
public sealed record AccountGetInput(string Id);
public sealed record FilterSetEnabledInput(string Id, bool Enabled, string IdempotencyKey);
public sealed record FiltersSetAllEnabledInput(bool Enabled, string IdempotencyKey);
public sealed record FilterCountsResetInput(string IdempotencyKey);
public sealed record FiltersMoveInput(string[] Ids, string Direction, string IdempotencyKey);
public sealed record FiltersCopyInput(string[] Ids, string IdempotencyKey);
public sealed record FilterCreateFromCaptureInput(long PacketId, string IdempotencyKey);
public sealed record FilterCreateInput(string IdempotencyKey);
public sealed record FilterRuleSaveInput(string Filter, JsonElement Rule, string IdempotencyKey);
public sealed record FilterDeleteInput(string Id, string IdempotencyKey);
public sealed record FilterGetInput(string Id);
public sealed record AccountSetEnabledInput(string Id, bool Enabled, string IdempotencyKey);
public sealed record AccountCreateInput(string UserName, string Password, bool Enabled, bool LimitLinksEnabled, int LimitLinks, bool LimitDevicesEnabled, int LimitDevices, bool ExpiryEnabled, string? ExpiryTime, string IdempotencyKey);
public sealed record AccountUpdateInput(string Id, bool Enabled, bool LimitLinksEnabled, int LimitLinks, bool LimitDevicesEnabled, int LimitDevices, bool ExpiryEnabled, string? ExpiryTime, string? Password, string IdempotencyKey);
public sealed record AccountDeleteInput(string Id, string IdempotencyKey);
public sealed record AccountLoginsListInput(string Id, int? Limit = null, string? Cursor = null);
public sealed record ProxyAuthSetEnabledInput(bool Enabled, string IdempotencyKey);
public sealed record ProxyHttpSetEnabledInput(bool Enabled, string IdempotencyKey);
public sealed record ProxyMaxConnectionsSetInput(int MaxConnection, string IdempotencyKey);
public sealed record ProxySocks5PortSetInput(int Port, string IdempotencyKey);
public sealed record ProxyHttpPortSetInput(int Port, string IdempotencyKey);
public sealed record FirewallSetEnabledInput(bool Enabled, string IdempotencyKey);
public sealed record ProxyOnlyWpcSetEnabledInput(bool Enabled, string IdempotencyKey);
public sealed record ProxyBindIpSetInput(bool Auto, string Ip, string IdempotencyKey);
public sealed record ExternalProxySetEnabledInput(bool Enabled, string IdempotencyKey);
public sealed record ProxyLifecycleInput(string IdempotencyKey);
public sealed record RemoteManagementSaveInput(bool Enabled, string Ip, int Port, string UserName, string Password, string IdempotencyKey);
public sealed record SettingGetInput(string Page, string? Mode);
public sealed record SettingSaveInput(string Page, JsonElement Values, string IdempotencyKey);
public sealed record MapLocalSaveInput(string Id, int Protocol, string Host, int Port, string RemotePath, string LocalPath, string IdempotencyKey);
public sealed record MapRemoteSaveInput(string Id, int ProtocolFrom, string HostFrom, int PortFrom, string PathFrom, int ProtocolTo, string HostTo, int PortTo, string PathTo, string IdempotencyKey);
public sealed record BackupExportInput(JsonElement Parts, string IdempotencyKey);
public sealed record WpcServerSaveInput(string? Id, bool Enabled, string Name, string Ip, int Port, string ForgotUrl, string RegisterUrl, string VerifyUrl, string IdempotencyKey);
public sealed record WpcServerRulesListInput(string ServerId);
public sealed record WpcServerRuleSaveInput(string ServerId, string? Id, bool Enabled, int Type, string Argument, int Action, string IdempotencyKey);
public sealed record ExecutorStopAllInput(string IdempotencyKey);
public sealed record CaptureListInput(string List, string IdempotencyKey);
public sealed record CaptureExportInput(string List, long[]? PacketIds, string IdempotencyKey, string? FileName = null);
public sealed record FilterFileInput(string IdempotencyKey, string? FileName = null);
public sealed record ImportInput(string Kind, string IdempotencyKey, string? FileName = null, string? SendId = null, string? WarehouseId = null);
public sealed record ExportInput(string Kind, string IdempotencyKey, string? FileName = null, JsonElement? BackupParts = null, string? CaptureList = null, long[]? CapturePacketIds = null, int? CertificateType = null, string? LogKind = null, string? SendId = null, string? WarehouseId = null, string[]? Ids = null, int? ExtractionKind = null, string? ExtractionText = null);
public sealed record InjectAttachInput(int Pid, string? Path, string? Args, int? Method, string IdempotencyKey);
public sealed record ProcessProxySaveInput(int DriverType, bool MustTcp, string? Ip, int Port, bool AppointPort, string? AppointPortContent, bool Auth, string? UserName, string? PassWord, int[]? Pids, string IdempotencyKey);
public sealed record PacketEditSendInput(string List, long Id, int Socket, string PayloadBase64, bool Continuous, int Times, int Interval, bool Progression, int Position, int Step, bool Carry, int CarryCount, string IdempotencyKey);
public sealed record StartModeSelectInput(string Mode, string IdempotencyKey);
public sealed record ProxyFailuresListInput(int? Limit = null);
public sealed record FirewallRulesListInput(string List, int? Limit = null, string? Cursor = null);
public sealed record FirewallRuleAddInput(string List, string Address, string IdempotencyKey, bool ExpiryEnabled = false, string? ExpiryTime = null);
public sealed record FirewallRuleRemoveInput(string List, string Address, string IdempotencyKey);
public sealed record PacketSearchInput(int? Limit = null, string? Cursor = null, string? Mode = null, string? Pattern = null, bool Hex = false, string Direction = "any");
public sealed record PacketGetInput(long Id, string? Mode = null, bool IncludePayload = false);
public sealed record CaptureFindNextInput(string Pattern, bool Hex = false, string Mode = "proxy", int FromIndex = 0, int FromPosition = 0);
public sealed record LogListInput(string Kind, int? Limit = null, string? Cursor = null);
public sealed record BytesTranscodeInput(string Text, bool Decode);
public sealed record BytesCompareInput(string Left, string Right, int MinimumRun = 2);
public sealed record BytesExtractInput(int Kind, string ContentBase64);
public sealed record EntityGetInput(string Id);
public sealed record EntityPageInput(string Id, int? Limit = null, string? Cursor = null);
public sealed record EntityEnabledInput(string Id, bool Enabled, string IdempotencyKey);
public sealed record TaskCreateInput(string Kind, string IdempotencyKey);
public sealed record TaskUpdateInput(string Kind, string Id, string Name, string IdempotencyKey, bool? UseSystemSocket = null, int? LoopCount = null, int? LoopInterval = null, string? Notes = null);
public sealed record TaskActionInput(string Kind, string[] Ids, string Direction, string IdempotencyKey);
public sealed record CaptureAddInput(string TargetId, long[] PacketIds, string IdempotencyKey);
public sealed record EntityWriteInput(string Id, string IdempotencyKey);
public sealed record SendCollectionActionInput(string SendId, string[] PacketIds, string Action, string IdempotencyKey);
public sealed record WarehouseStoresActionInput(string WarehouseId, string[] StoreIds, string Action, string IdempotencyKey);
public sealed record RobotInstructionAddInput(string Robot, int Type, string Content, int InsertAt, string IdempotencyKey);
public sealed record RobotInstructionsSaveInput(string Robot, JsonElement Instructions, string IdempotencyKey);
public sealed record RobotInstructionActionInput(string RobotId, int[] Indexes, string Action, string IdempotencyKey);
public sealed record AutoStoresSaveInput(string? Id, string PacketHead, string WarehouseId, string IdempotencyKey);
public sealed record WarehouseCommandInput(string WarehouseId, string Action, string IdempotencyKey);
public sealed record PacketEditGetInput(string List, long Id);
public sealed record PacketEditSaveInput(string List, long Id, int Socket, string PayloadBase64, string IdempotencyKey);
public sealed record PacketEditAddToSendInput(string SendId, string List, long Id, string PayloadBase64, string IdempotencyKey);
